/**
 * 后台设置面板 - 设置单元清单
 *
 * 一个「设置单元」对应设置面板左侧导航里的一项。
 * 本文件只描述元信息（不 import 配置本体），因此可以安全地打进客户端产物。
 */

import type { SettingsUnitMeta } from "@/types/adminSettings";

/** 变量所在源文件：生成配置代码时按此定位 */
export const CONFIG_FILE_OF: Record<string, string> = {
	siteConfig: "src/config/siteConfig.ts",
	displaySettingsConfig: "src/config/displaySettingsConfig.ts",
	profileConfig: "src/config/profileConfig.ts",
	backgroundWallpaper: "src/config/backgroundWallpaper.ts",
	navBarConfig: "src/config/navBarConfig.ts",
	navBarSearchConfig: "src/config/navBarConfig.ts",
	sidebarLayoutConfig: "src/config/sidebarConfig.ts",
	fontConfig: "src/config/fontConfig.ts",
	coverImageConfig: "src/config/coverImageConfig.ts",
	sakuraConfig: "src/config/effectsConfig.ts",
	commentConfig: "src/config/commentConfig.ts",
	analyticsConfig: "src/config/analyticsConfig.ts",
	musicPlayerConfig: "src/config/musicConfig.ts",
	live2dWidgetConfig: "src/config/pioConfig.ts",
	sponsorConfig: "src/config/sponsorConfig.ts",
	friendsConfig: "src/config/friendsConfig.ts",
	galleryConfig: "src/config/galleryConfig.ts",
	booknavConfig: "src/config/booknavConfig.ts",
	announcementConfig: "src/config/announcementConfig.ts",
	dynamicConfig: "src/config/dynamicConfig.ts",
	footerConfig: "src/config/footerConfig.ts",
	licenseConfig: "src/config/licenseConfig.ts",
	expressiveCodeConfig: "src/config/expressiveCodeConfig.ts",
	mermaidConfig: "src/config/mermaidConfig.ts",
	plantumlConfig: "src/config/plantumlConfig.ts",
	adminConfig: "src/config/adminConfig.ts",
};

/** 设置单元的显示顺序与分组 */
export const SETTINGS_UNITS: SettingsUnitMeta[] = [
	// ── 核心 ──────────────────────────────────────────────
	{
		id: "site-basic",
		label: "基础配置",
		description: "站点标题、描述、语言、主题色等最基础的信息",
		icon: "settings",
		group: "core",
		file: CONFIG_FILE_OF.siteConfig,
		varName: "siteConfig",
		fields: [
			"title",
			"subtitle",
			"site_url",
			"description",
			"keywords",
			"lang",
			"timezone",
			"siteStartDate",
			"themeColor",
			"pageWidth",
			"card",
			"favicon",
		],
		kind: "form",
		editor: "siteBasic",
	},
	{
		id: "site-advanced",
		label: "站点配置",
		description: "导航栏、页面开关、文章列表、文章内容、第三方数据与图像优化",
		icon: "post",
		group: "core",
		file: CONFIG_FILE_OF.siteConfig,
		varName: "siteConfig",
		fields: [
			"navbar",
			"pages",
			"categoryBar",
			"categoryStyle",
			"tagStyle",
			"foldArticle",
			"postListLayout",
			"pagination",
			"post",
			"feed",
			"imageOptimization",
			"bilibili",
			"bangumi",
			"vndb",
			"mal",
		],
		kind: "form",
		editor: "siteAdvanced",
	},
	{
		id: "display-settings",
		label: "设置面板",
		description: "控制前台「显示设置」面板里出现哪些开关项",
		icon: "dashboard",
		group: "core",
		file: CONFIG_FILE_OF.displaySettingsConfig,
		varName: "displaySettingsConfig",
		kind: "form",
		editor: "displaySettings",
	},

	// ── 外观 ──────────────────────────────────────────────
	{
		id: "profile",
		label: "个人资料",
		description: "头像、昵称、签名与社交链接",
		icon: "user",
		group: "appearance",
		file: CONFIG_FILE_OF.profileConfig,
		varName: "profileConfig",
		kind: "form",
		editor: "profile",
	},
	{
		id: "wallpaper",
		label: "背景壁纸",
		description: "壁纸模式、桌面端与移动端壁纸、横幅文字与轮播",
		icon: "image",
		group: "appearance",
		file: CONFIG_FILE_OF.backgroundWallpaper,
		varName: "backgroundWallpaper",
		kind: "form",
		editor: "wallpaper",
	},
	{
		id: "font",
		label: "字体配置",
		description: "全站字体选择",
		icon: "text",
		group: "appearance",
		file: CONFIG_FILE_OF.fontConfig,
		varName: "fontConfig",
		kind: "form",
	},
	{
		id: "cover-image",
		label: "封面图配置",
		description: "文章封面的默认行为",
		icon: "image",
		group: "appearance",
		file: CONFIG_FILE_OF.coverImageConfig,
		varName: "coverImageConfig",
		kind: "form",
	},
	{
		id: "effects",
		label: "动画特效",
		description: "樱花飘落等页面特效",
		icon: "sparkles",
		group: "appearance",
		file: CONFIG_FILE_OF.sakuraConfig,
		varName: "sakuraConfig",
		kind: "form",
	},

	// ── 布局 ──────────────────────────────────────────────
	{
		id: "navbar",
		label: "导航栏",
		description: "导航菜单项与子菜单，支持拖拽排序",
		icon: "menu",
		group: "layout",
		file: CONFIG_FILE_OF.navBarConfig,
		varName: "navBarConfig",
		kind: "form",
		editor: "navbar",
	},
	{
		id: "navbar-search",
		label: "导航搜索",
		description: "导航栏搜索使用的检索方式",
		icon: "search",
		group: "layout",
		file: CONFIG_FILE_OF.navBarConfig,
		varName: "navBarSearchConfig",
		kind: "form",
	},
	{
		id: "sidebar",
		label: "侧边栏",
		description: "侧边栏位置与响应式显示规则",
		icon: "layout",
		group: "layout",
		file: CONFIG_FILE_OF.sidebarLayoutConfig,
		varName: "sidebarLayoutConfig",
		fields: [
			"enable",
			"position",
			"tabletSidebar",
			"hideSidebarOnPostPage",
			"showBothSidebarsOnPostPage",
		],
		kind: "form",
		editor: "sidebar",
	},
	{
		id: "sidebar-widgets",
		label: "侧边栏小组件",
		description: "左右侧边栏与移动端底部的组件，支持启用、排序与参数配置",
		icon: "grid",
		group: "layout",
		file: CONFIG_FILE_OF.sidebarLayoutConfig,
		varName: "sidebarLayoutConfig",
		fields: ["leftComponents", "rightComponents", "mobileBottomComponents"],
		kind: "form",
		editor: "widgets",
	},

	// ── 功能 ──────────────────────────────────────────────
	{
		id: "comment",
		label: "评论系统",
		description: "文章评论使用的服务商与参数",
		icon: "chat",
		group: "feature",
		file: CONFIG_FILE_OF.commentConfig,
		varName: "commentConfig",
		kind: "form",
	},
	{
		id: "announcement",
		label: "站点公告",
		description: "侧边栏公告卡片内容",
		icon: "alert",
		group: "feature",
		file: CONFIG_FILE_OF.announcementConfig,
		varName: "announcementConfig",
		kind: "form",
	},
	{
		id: "music",
		label: "音乐播放器",
		description: "侧边栏音乐播放器",
		icon: "music",
		group: "feature",
		file: CONFIG_FILE_OF.musicPlayerConfig,
		varName: "musicPlayerConfig",
		kind: "form",
	},
	{
		id: "live2d",
		label: "看板娘",
		description: "Live2D 看板娘角色",
		icon: "user",
		group: "feature",
		file: CONFIG_FILE_OF.live2dWidgetConfig,
		varName: "live2dWidgetConfig",
		kind: "form",
	},
	{
		id: "sponsor",
		label: "打赏赞助",
		description: "打赏页面的收款方式",
		icon: "gift",
		group: "feature",
		file: CONFIG_FILE_OF.sponsorConfig,
		varName: "sponsorConfig",
		kind: "form",
	},
	{
		id: "friends",
		label: "友情链接",
		description: "友链页面展示的站点列表",
		icon: "link",
		group: "feature",
		file: CONFIG_FILE_OF.friendsConfig,
		varName: "friendsConfig",
		kind: "list",
	},
	{
		id: "gallery",
		label: "相册",
		description: "相册页面的分组与图片",
		icon: "image",
		group: "feature",
		file: CONFIG_FILE_OF.galleryConfig,
		varName: "galleryConfig",
		kind: "form",
	},
	{
		id: "booknav",
		label: "书签导航",
		description: "书签导航页的分组与条目",
		icon: "bookmark",
		group: "feature",
		file: CONFIG_FILE_OF.booknavConfig,
		varName: "booknavConfig",
		kind: "list",
	},
	{
		id: "dynamic",
		label: "动态页面",
		description: "「动态」页面的展示配置",
		icon: "post",
		group: "feature",
		file: CONFIG_FILE_OF.dynamicConfig,
		varName: "dynamicConfig",
		kind: "form",
	},
	{
		id: "footer",
		label: "页脚配置",
		description: "页脚展示的信息",
		icon: "layout",
		group: "feature",
		file: CONFIG_FILE_OF.footerConfig,
		varName: "footerConfig",
		kind: "form",
	},
	{
		id: "license",
		label: "版权许可",
		description: "文章默认的版权协议",
		icon: "shield",
		group: "feature",
		file: CONFIG_FILE_OF.licenseConfig,
		varName: "licenseConfig",
		kind: "form",
	},

	// ── 高级 ──────────────────────────────────────────────
	{
		id: "analytics",
		label: "统计分析",
		description: "站点统计与访客分析",
		icon: "chart",
		group: "advanced",
		file: CONFIG_FILE_OF.analyticsConfig,
		varName: "analyticsConfig",
		kind: "form",
	},
	{
		id: "code-highlight",
		label: "代码高亮",
		description: "代码块样式与功能",
		icon: "code",
		group: "advanced",
		file: CONFIG_FILE_OF.expressiveCodeConfig,
		varName: "expressiveCodeConfig",
		kind: "form",
	},
	{
		id: "mermaid",
		label: "Mermaid 图表",
		description: "Mermaid 图表渲染配置",
		icon: "chart",
		group: "advanced",
		file: CONFIG_FILE_OF.mermaidConfig,
		varName: "mermaidConfig",
		kind: "form",
	},
	{
		id: "plantuml",
		label: "PlantUML 图表",
		description: "PlantUML 图表渲染配置",
		icon: "chart",
		group: "advanced",
		file: CONFIG_FILE_OF.plantumlConfig,
		varName: "plantumlConfig",
		kind: "form",
	},
	{
		id: "admin-config",
		label: "后台管理",
		description: "后台入口开关、会话时长、GitHub 发布默认值",
		icon: "lock",
		group: "advanced",
		file: CONFIG_FILE_OF.adminConfig,
		varName: "adminConfig",
		kind: "form",
	},
];

/** 分组显示名与顺序 */
export const SETTINGS_GROUPS: {
	id: SettingsUnitMeta["group"];
	label: string;
	description: string;
}[] = [
	{ id: "core", label: "核心", description: "站点基础信息与前台设置面板" },
	{ id: "appearance", label: "外观", description: "个人资料、壁纸、字体与特效" },
	{ id: "layout", label: "布局", description: "导航栏与侧边栏" },
	{ id: "feature", label: "功能", description: "评论、友链、相册等站点功能" },
	{ id: "advanced", label: "高级", description: "统计、代码高亮与图表渲染" },
];
